[build-system]
requires = ["wheel"]

[project]
authors = [
	{name = "Kamil Democko", email = "kamil.democko@gmail.com"}
]
description = "Automate SAP with python!"
readme = {file = "README.md", content-type = "text/markdown"}
licence = {file = "licence.txt", content-type = "text"}
keywords = ["sap", "sap script", "sapscript", "automation", "robot"]

[project.urls]
Repository = "https://github.com/kamildemocko/pysapscript"

[tool.poetry]
name = "pysapscript"
version = "2.1.3"
description = "Automate SAP with python!"
authors = ["Kamil Democko <kamil.democko@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^2.0.0"
pywin32 = "^306"
pdoc = "^14.3.0"

